# Pandas.json

#### link for pandas.json-https://pandas.pydata.org/docs/reference/api/pandas.read_json.html

In [2]:
import pandas as pd

In [6]:
pd.read_json(r'C:\Users\Aman Sahu\OneDrive\Desktop\ml-journey\Day4_Working_with_JSON&SQL\Dataset\train.json')

          id      cuisine                                        ingredients
0      10259        greek  [romaine lettuce, black olives, grape tomatoes...
1      25693  southern_us  [plain flour, ground pepper, salt, tomatoes, g...
2      20130     filipino  [eggs, pepper, salt, mayonaise, cooking oil, g...
3      22213       indian                [water, vegetable oil, wheat, salt]
4      13162       indian  [black pepper, shallots, cornflour, cayenne pe...
...      ...          ...                                                ...
39769  29109        irish  [light brown sugar, granulated sugar, butter, ...
39770  11462      italian  [KRAFT Zesty Italian Dressing, purple onion, b...
39771   2238        irish  [eggs, citrus fruit, raisins, sourdough starte...
39772  41882      chinese  [boneless chicken skinless thigh, minced garli...
39773   2362      mexican  [green chile, jalapeno chilies, onions, ground...

[39774 rows x 3 columns]

In [11]:
pd.read_json('https://api.exchangerate-api.com/v4/latest/INR')

,provider,WARNING_UPGRADE_TO_V6,terms,base,date,time_last_updated,rates
INR,https://www.exchangerate-api.com,https://www.exchangerate-api.com/docs/free,https://www.exchangerate-api.com/terms,INR,2025-05-01,1746057601,1.0000
AED,https://www.exchangerate-api.com,https://www.exchangerate-api.com/docs/free,https://www.exchangerate-api.com/terms,INR,2025-05-01,1746057601,0.0434
AFN,https://www.exchangerate-api.com,https://www.exchangerate-api.com/docs/free,https://www.exchangerate-api.com/terms,INR,2025-05-01,1746057601,0.8350
ALL,https://www.exchangerate-api.com,https://www.exchangerate-api.com/docs/free,https://www.exchangerate-api.com/terms,INR,2025-05-01,1746057601,1.0200
AMD,https://www.exchangerate-api.com,https://www.exchangerate-api.com/docs/free,https://www.exchangerate-api.com/terms,INR,2025-05-01,1746057601,4.6000
...,...,...,...,...,...,...,...
XPF,https://www.exchangerate-api.com,https://www.exchangerate-api.com/docs/free,https://www.exchangerate-api.com/terms,INR,2025-05-01,1746057601,1.2400
YER,https://www.exchangerate-api.com,https://www.exchangerate-api.com/docs/free,https://www.exchangerate-api.com/terms,INR,2025-05-01,1746057601,2.8800
ZAR,https://www.exchangerate-api.com,https://www.exchangerate-api.com/docs/free,https://www.exchangerate-api.com/terms,INR,2025-05-01,1746057601,0.2200
ZMW,https://www.exchangerate-api.com,https://www.exchangerate-api.com/docs/free,https://www.exchangerate-api.com/terms,INR,2025-05-01,1746057601,0.3290
ZWL,https://www.exchangerate-api.com,https://www.exchangerate-api.com/docs/free,https://www.exchangerate-api.com/terms,INR,2025-05-01,1746057601,0.3170

# working with sequel

In [14]:
pip install mysql.connector

Collecting mysql.connector
  Downloading mysql-connector-2.2.9.tar.gz (11.9 MB)
     ---------------------------------------- 0.0/11.9 MB ? eta -:--:--
     ----- ---------------------------------- 1.6/11.9 MB 12.0 MB/s eta 0:00:01
     --------------- ------------------------ 4.5/11.9 MB 12.8 MB/s eta 0:00:01
     ----------------- ---------------------- 5.2/11.9 MB 9.4 MB/s eta 0:00:01
     ------------------- -------------------- 5.8/11.9 MB 7.3 MB/s eta 0:00:01
     ------------------------- -------------- 7.6/11.9 MB 7.6 MB/s eta 0:00:01
     --------------------------- ------------ 8.1/11.9 MB 6.8 MB/s eta 0:00:01
     ------------------------------ --------- 8.9/11.9 MB 6.5 MB/s eta 0:00:01
     -------------------------------- ------- 9.7/11.9 MB 6.2 MB/s eta 0:00:01
     ------------------------------------ --- 10.7/11.9 MB 5.8 MB/s eta 0:00:01
     ---------------------------------------  11.8/11.9 MB 5.7 MB/s eta 0:00:01
     ---------------------------------------- 11.9/11.9 MB 5.5 MB/s eta 0:00:00
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'done'
Building wheels for collected packages: mysql.connector
  Building wheel for mysql.connector (setup.py): started
  Building wheel for mysql.connector (setup.py): finished with status 'done'
  Created wheel for mysql.connector: filename=mysql_connector-2.2.9-cp312-cp312-win_amd64.whl size=247959 sha256=dbda28918d8db33c6d9765d7d4071b948d7428ac8222d8b9dbf0e86fe1c28361
  Stored in directory: c:\users\aman sahu\appdata\local\pip\cache\wheels\03\17\fa\d7604c72dd3dd6d3eb3d249abf36cc532c9a9b4354b8f1bc4f
Successfully built mysql.connector
Installing collected packages: mysql.connector
Successfully installed mysql.connector-2.2.9
Note: you may need to restart the kernel to use updated packages.